spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: taejin
    password: taejin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true # jpa sql 줄바꿈 여부
        use_sql_comments: true # 주석까지 출력 여부
        default_schema: security1 # 스키마 지정
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always



jwt:
  secret: 6RS1Db21tZXJjZQ==

  #JPA log
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: ERROR
        SQL: INFO
        type: INFO
